gateway.uri=http://localhost:9900
#RemoteService URI
#friend.uri=http://localhost:9300/customers/
#plan.uri=http://localhost:9400/plans/

management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
